<!-- VIEW: AGENDA INSTRUCTOR (HU-08, HU-09) -->
<div class="view-content" id="view-agenda-instructor">

  <div class="welcome-card-header">
    <div style="display: flex; align-items: center; gap: 14px;">
      <div class="kpi-icon-wrapper" style="background: rgba(255,255,255,0.15); color: #FFFFFF; font-size: 24px;">
        <i data-lucide="calendar"></i>
      </div>
      <div>
        <h1>Agenda de Seguimiento</h1>
        <p>Programa visitas empresariales y registra los resultados del seguimiento a tus aprendices.</p>
      </div>
    </div>
  </div>

  <div class="grid-2" style="margin-bottom: 24px; gap: 24px; align-items: start;">

    <!-- Left: Calendar / Slots -->
    <div class="card" style="padding: 24px;">
      <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;">
        <h3 style="font-size:15px;">Programar Visita</h3>
        <button class="btn btn-primary btn-sm" onclick="openModal('modalNewVisit')">
          <i data-lucide="plus"></i> Nueva Visita
        </button>
      </div>

      <!-- Compact calendar header -->
      <div style="background:var(--bg-secondary);border-radius:10px;padding:16px;margin-bottom:16px;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;">
          <button class="btn btn-ghost btn-sm" onclick="showToast('Mes anterior','info')"><i data-lucide="chevron-left"></i></button>
          <h4 style="font-size:14px;">Junio 2026</h4>
          <button class="btn btn-ghost btn-sm" onclick="showToast('Mes siguiente','info')"><i data-lucide="chevron-right"></i></button>
        </div>
        <div style="display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center;font-size:11px;color:var(--text-muted);margin-bottom:8px;">
          <span>L</span><span>M</span><span>X</span><span>J</span><span>V</span><span>S</span><span>D</span>
        </div>
        <div id="calendarGrid" style="display:grid;grid-template-columns:repeat(7,1fr);gap:4px;text-align:center;font-size:12px;">
          <!-- Days will be generated by JS -->
        </div>
      </div>

      <!-- Availability slots -->
      <div>
        <h4 style="font-size:13px;margin-bottom:12px;color:var(--text-secondary);">Horarios Disponibles</h4>
        <form id="availabilityForm" novalidate onsubmit="event.preventDefault(); saveAvailability();">
          <div class="form-group">
            <label class="form-label" for="availDate">Fecha *</label>
            <input type="date" id="availDate" class="form-control" required min="2026-06-14">
            <span class="form-error-text" id="availDateError">Seleccione una fecha válida.</span>
          </div>
          <div class="grid-2">
            <div class="form-group">
              <label class="form-label" for="availStart">Hora inicio *</label>
              <input type="time" id="availStart" class="form-control" required>
              <span class="form-error-text" id="availStartError">Ingrese hora de inicio.</span>
            </div>
            <div class="form-group">
              <label class="form-label" for="availEnd">Hora fin *</label>
              <input type="time" id="availEnd" class="form-control" required>
              <span class="form-error-text" id="availEndError">Ingrese hora de fin.</span>
            </div>
          </div>
          <div class="form-group">
            <label class="form-label" for="availType">Tipo de Seguimiento *</label>
            <select id="availType" class="form-control" required>
              <option value="">Seleccionar...</option>
              <option value="visita">Visita Empresarial</option>
              <option value="virtual">Seguimiento Virtual</option>
              <option value="presencial">Reunión Presencial SENA</option>
            </select>
          </div>
          <button type="submit" class="btn btn-primary" style="width:100%;">
            <i data-lucide="save"></i> Guardar Disponibilidad
          </button>
        </form>
      </div>
    </div>

    <!-- Right: Upcoming visits -->
    <div style="display:flex;flex-direction:column;gap:16px;">
      <div class="card" style="padding:24px;">
        <h3 style="font-size:15px;margin-bottom:16px;">Próximas Visitas</h3>
        <div style="display:flex;flex-direction:column;gap:12px;" id="upcomingVisitsList">

          <div class="alert alert-info" style="margin:0;cursor:pointer;" onclick="openVisitDetail('Carlos Guerrero','20/06/2026','10:00','TechCorp S.A.S.','Visita')">
            <i data-lucide="calendar-check"></i>
            <div style="flex:1;">
              <div class="alert-title">Carlos Guerrero</div>
              <div style="font-size:11px;">20/06/2026 · 10:00 AM · TechCorp S.A.S.</div>
              <span class="badge badge-info" style="margin-top:4px;font-size:10px;">Visita Empresarial</span>
            </div>
            <button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();openRegisterResult('Carlos Guerrero')" title="Registrar resultado">
              <i data-lucide="clipboard-edit"></i>
            </button>
          </div>

          <div class="alert alert-success" style="margin:0;cursor:pointer;" onclick="openVisitDetail('Sara Ramírez','22/06/2026','14:00','DigitalPyme SAS','Virtual')">
            <i data-lucide="video"></i>
            <div style="flex:1;">
              <div class="alert-title">Sara Ramírez</div>
              <div style="font-size:11px;">22/06/2026 · 02:00 PM · DigitalPyme SAS</div>
              <span class="badge badge-success" style="margin-top:4px;font-size:10px;">Seguimiento Virtual</span>
            </div>
            <button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();openRegisterResult('Sara Ramírez')" title="Registrar resultado">
              <i data-lucide="clipboard-edit"></i>
            </button>
          </div>

          <div class="alert alert-warning" style="margin:0;cursor:pointer;" onclick="openVisitDetail('Laura Martínez','25/06/2026','09:00','Innova Digital','Visita')">
            <i data-lucide="alert-triangle"></i>
            <div style="flex:1;">
              <div class="alert-title">Laura Martínez <span style="font-size:11px;color:var(--status-danger);">⚠ En riesgo</span></div>
              <div style="font-size:11px;">25/06/2026 · 09:00 AM · Innova Digital</div>
              <span class="badge badge-warning" style="margin-top:4px;font-size:10px;">Visita Prioritaria</span>
            </div>
            <button class="btn btn-ghost btn-sm" onclick="event.stopPropagation();openRegisterResult('Laura Martínez')" title="Registrar resultado">
              <i data-lucide="clipboard-edit"></i>
            </button>
          </div>

        </div>
      </div>

      <!-- Registered results history -->
      <div class="card" style="padding:24px;">
        <h3 style="font-size:15px;margin-bottom:16px;">Historial de Seguimientos</h3>
        <div class="table-wrapper">
          <table class="table" style="font-size:12px;">
            <thead>
              <tr>
                <th>Aprendiz</th>
                <th>Fecha</th>
                <th>Tipo</th>
                <th>Resultado</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Carlos Guerrero</td>
                <td>05/06/2026</td>
                <td>Virtual</td>
                <td><span class="badge badge-success">Favorable</span></td>
              </tr>
              <tr>
                <td>Jhon Pérez</td>
                <td>03/06/2026</td>
                <td>Visita</td>
                <td><span class="badge badge-warning">Con observaciones</span></td>
              </tr>
              <tr>
                <td>Laura Martínez</td>
                <td>28/05/2026</td>
                <td>Visita</td>
                <td><span class="badge badge-danger">En riesgo</span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <!-- MODAL: NUEVA VISITA -->
  <div class="modal-overlay" id="modalNewVisit">
    <div class="modal-container">
      <div class="modal-header">
        <h3><i data-lucide="calendar-plus" style="width:18px;height:18px;margin-right:8px;vertical-align:middle;"></i>Programar Visita de Seguimiento</h3>
        <button class="modal-close" onclick="closeModal('modalNewVisit')"><i data-lucide="x"></i></button>
      </div>
      <div class="modal-body">
        <form id="newVisitForm" novalidate onsubmit="event.preventDefault(); scheduleVisit();">
          <div class="form-group">
            <label class="form-label" for="visitAprendiz">Aprendiz *</label>
            <select id="visitAprendiz" class="form-control" required>
              <option value="">Seleccionar aprendiz...</option>
              <option>Carlos Guerrero</option>
              <option>Laura Martínez</option>
              <option>Jhon Pérez</option>
              <option>Sara Ramírez</option>
            </select>
            <span class="form-error-text" id="visitAprendizError">Seleccione un aprendiz.</span>
          </div>
          <div class="grid-2">
            <div class="form-group">
              <label class="form-label" for="visitDate">Fecha *</label>
              <input type="date" id="visitDate" class="form-control" required min="2026-06-14">
              <span class="form-error-text" id="visitDateError">Seleccione una fecha.</span>
            </div>
            <div class="form-group">
              <label class="form-label" for="visitTime">Hora *</label>
              <input type="time" id="visitTime" class="form-control" required>
              <span class="form-error-text" id="visitTimeError">Seleccione una hora.</span>
            </div>
          </div>
          <div class="form-group">
            <label class="form-label" for="visitType2">Modalidad *</label>
            <select id="visitType2" class="form-control" required>
              <option value="">Seleccionar...</option>
              <option>Visita Empresarial</option>
              <option>Seguimiento Virtual</option>
              <option>Reunión Presencial SENA</option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-label" for="visitNotes">Objetivo de la visita</label>
            <textarea id="visitNotes" class="form-control" rows="3" placeholder="Describir el propósito principal de esta visita..."></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-ghost" onclick="closeModal('modalNewVisit')">Cancelar</button>
        <button type="submit" form="newVisitForm" class="btn btn-primary"><i data-lucide="check"></i> Confirmar Visita</button>
      </div>
    </div>
  </div>

  <!-- MODAL: REGISTRAR RESULTADO -->
  <div class="modal-overlay" id="modalRegisterResult">
    <div class="modal-container">
      <div class="modal-header">
        <h3><i data-lucide="clipboard-edit" style="width:18px;height:18px;margin-right:8px;vertical-align:middle;"></i>Registrar Resultado de Seguimiento</h3>
        <button class="modal-close" onclick="closeModal('modalRegisterResult')"><i data-lucide="x"></i></button>
      </div>
      <div class="modal-body">
        <p style="font-size:13px;color:var(--text-muted);margin-bottom:16px;">Aprendiz: <strong id="resultAprendiz">Carlos Guerrero</strong></p>
        <form id="resultForm" novalidate onsubmit="event.preventDefault(); saveResult();">
          <div class="form-group">
            <label class="form-label" for="resultOutcome">Resultado General *</label>
            <select id="resultOutcome" class="form-control" required>
              <option value="">Seleccionar resultado...</option>
              <option value="favorable">Favorable — Sin observaciones</option>
              <option value="observaciones">Con observaciones — Requiere seguimiento</option>
              <option value="riesgo">En riesgo — Requiere intervención inmediata</option>
            </select>
            <span class="form-error-text" id="resultOutcomeError">Seleccione el resultado.</span>
          </div>
          <div class="form-group">
            <label class="form-label" for="resultObservations">Observaciones Detalladas *</label>
            <textarea id="resultObservations" class="form-control" rows="4" placeholder="Describa el desempeño del aprendiz, condiciones de la empresa, novedades encontradas..." required></textarea>
            <span class="form-error-text" id="resultObsError">Las observaciones son obligatorias.</span>
          </div>
          <div class="form-group">
            <label class="form-label" for="resultActions">Acciones de Mejora (si aplica)</label>
            <textarea id="resultActions" class="form-control" rows="2" placeholder="Compromisos adquiridos por el aprendiz o la empresa..."></textarea>
          </div>
          <div class="form-group">
            <label class="form-label">Evidencia fotográfica (opcional)</label>
            <div class="dropzone" id="resultDropzone" style="padding:16px;">
              <i data-lucide="image"></i>
              <p class="dropzone-title" style="font-size:13px;">Adjuntar fotos de la visita</p>
              <p class="dropzone-sub">JPG, PNG · Máx. 5MB c/u</p>
              <input type="file" id="resultFile" accept=".jpg,.jpeg,.png" multiple style="display:none;">
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button class="btn btn-ghost" onclick="closeModal('modalRegisterResult')">Cancelar</button>
        <button type="submit" form="resultForm" class="btn btn-primary"><i data-lucide="save"></i> Guardar Resultado</button>
      </div>
    </div>
  </div>

  <!-- MODAL: DETALLE VISITA -->
  <div class="modal-overlay" id="modalVisitDetail">
    <div class="modal-container" style="max-width:480px;">
      <div class="modal-header">
        <h3><i data-lucide="info" style="width:18px;height:18px;margin-right:8px;vertical-align:middle;"></i>Detalle de la Visita</h3>
        <button class="modal-close" onclick="closeModal('modalVisitDetail')"><i data-lucide="x"></i></button>
      </div>
      <div class="modal-body">
        <div class="grid-2" style="margin-bottom:16px;">
          <div>
            <p style="font-size:12px;color:var(--text-muted);">Aprendiz</p>
            <p style="font-weight:600;" id="detailAprendiz">Carlos Guerrero</p>
          </div>
          <div>
            <p style="font-size:12px;color:var(--text-muted);">Empresa</p>
            <p style="font-weight:600;" id="detailEmpresa">TechCorp S.A.S.</p>
          </div>
          <div>
            <p style="font-size:12px;color:var(--text-muted);">Fecha y Hora</p>
            <p style="font-weight:600;" id="detailFecha">20/06/2026 · 10:00 AM</p>
          </div>
          <div>
            <p style="font-size:12px;color:var(--text-muted);">Modalidad</p>
            <p style="font-weight:600;" id="detailTipo">Visita Empresarial</p>
          </div>
        </div>
        <div class="alert alert-info" style="margin:0;">
          <i data-lucide="info"></i>
          <div>La visita está programada. Recuerde registrar el resultado después de realizarla.</div>
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn btn-ghost" onclick="closeModal('modalVisitDetail')">Cerrar</button>
        <button class="btn btn-danger" onclick="closeModal('modalVisitDetail'); showToast('Visita cancelada.','warning')">
          <i data-lucide="x-circle"></i> Cancelar Visita
        </button>
      </div>
    </div>
  </div>

</div>

<script>
// Draw calendar
(function buildCalendar() {
  const grid = document.getElementById('calendarGrid');
  if (!grid) return;
  const startDay = 1; // June 2026 starts on Monday
  const daysInMonth = 30;
  const bookedDays = [20, 22, 25];
  let html = '';
  for (let i = 0; i < startDay - 1; i++) html += '<span></span>';
  for (let d = 1; d <= daysInMonth; d++) {
    const isBooked = bookedDays.includes(d);
    const isToday = d === 14;
    html += `<span style="
      padding:5px 2px;border-radius:6px;cursor:pointer;
      background:${isBooked ? 'var(--primary)' : isToday ? 'var(--bg-card)' : 'transparent'};
      color:${isBooked ? '#fff' : isToday ? 'var(--primary)' : 'var(--text-primary)'};
      font-weight:${isBooked || isToday ? '700' : '400'};
      border:${isToday && !isBooked ? '1px solid var(--primary)' : 'none'};
    " onclick="showToast('Día ${d} de Junio 2026','info')">${d}</span>`;
  }
  grid.innerHTML = html;
})();

function saveAvailability() {
  const date = document.getElementById('availDate').value;
  const start = document.getElementById('availStart').value;
  const end = document.getElementById('availEnd').value;
  const type = document.getElementById('availType').value;
  let valid = true;
  if (!date) { document.getElementById('availDateError').style.display='block'; valid=false; }
  else document.getElementById('availDateError').style.display='none';
  if (!start) { document.getElementById('availStartError').style.display='block'; valid=false; }
  else document.getElementById('availStartError').style.display='none';
  if (!end || end <= start) { document.getElementById('availEndError').style.display='block'; valid=false; }
  else document.getElementById('availEndError').style.display='none';
  if (!valid) return;
  showToast('Disponibilidad guardada exitosamente.', 'success');
  document.getElementById('availabilityForm').reset();
}

function scheduleVisit() {
  const aprendiz = document.getElementById('visitAprendiz').value;
  const date = document.getElementById('visitDate').value;
  const time = document.getElementById('visitTime').value;
  let valid = true;
  if (!aprendiz) { document.getElementById('visitAprendizError').style.display='block'; valid=false; }
  else document.getElementById('visitAprendizError').style.display='none';
  if (!date) { document.getElementById('visitDateError').style.display='block'; valid=false; }
  else document.getElementById('visitDateError').style.display='none';
  if (!time) { document.getElementById('visitTimeError').style.display='block'; valid=false; }
  else document.getElementById('visitTimeError').style.display='none';
  if (!valid) return;
  showToast(`Visita programada para ${aprendiz} el ${date} a las ${time}.`, 'success');
  closeModal('modalNewVisit');
  document.getElementById('newVisitForm').reset();
}

function openRegisterResult(name) {
  document.getElementById('resultAprendiz').textContent = name;
  openModal('modalRegisterResult');
}

function saveResult() {
  const outcome = document.getElementById('resultOutcome').value;
  const obs = document.getElementById('resultObservations').value.trim();
  let valid = true;
  if (!outcome) { document.getElementById('resultOutcomeError').style.display='block'; valid=false; }
  else document.getElementById('resultOutcomeError').style.display='none';
  if (!obs) { document.getElementById('resultObsError').style.display='block'; valid=false; }
  else document.getElementById('resultObsError').style.display='none';
  if (!valid) return;
  showToast('Resultado de seguimiento registrado correctamente.', 'success');
  closeModal('modalRegisterResult');
  document.getElementById('resultForm').reset();
}

function openVisitDetail(aprendiz, fecha, hora, empresa, tipo) {
  document.getElementById('detailAprendiz').textContent = aprendiz;
  document.getElementById('detailEmpresa').textContent = empresa;
  document.getElementById('detailFecha').textContent = fecha + ' · ' + hora;
  document.getElementById('detailTipo').textContent = tipo;
  openModal('modalVisitDetail');
}
</script>
